INSERT INTO `english_hanja_definition` VALUES
('家', 'a dwelling'),
('腔', 'atrium, cavity'),
('鋼', 'steel'),
('講', 'a recitation or recital'),
('開', 'to open'),
('件', 'sth presented as a problem'),
('岒', 'sword, saber, dagger'),
('經', 'sutra, a religious text'),
('犒', 'late'),
('犒', 'deceased'),
('骨', 'the marrow (of bones)'),
('功', 'meritorious labors, good labors, good efforts'),
('管', 'duct, pipe, tube'),
('官', 'sth to do with the government'),
('棺', 'coffin'),
('款', 'an article/conditions of the law'),
('冠', 'corona, king`s crown'),
('觀', 'outlook, point of view'),
('館', 'a large hall'),
('鞫', 'department'),
('矻', 'cave'),
('矻', 'oyster'),
('鈐', 'aurum, yellow metal, gold'),
('亘', 'affirmation'),
('期', 'an era, a time frame'),
('基', 'radical'),
('旗', 'banner, flag, a bunting, a gonfalon, standard'),
('氣', 'tinge, tint; mist; energy'),
('囊', 'bursa, sac'),
('綠', 'rust, patina, tarnish'),
('祿', 'a stipend'),
('啂', 'sack'),
('代', 'era, period'),
('代', 'an era, generation, reign of a king, Greater, being absolutely huge,'),
('代', 'a generation'),
('對', '1) Versus 2) a pair, counterpart'),
('圖', 'a picture, diagram'),
('宊', 'rock, stone (宊 [ 집 가,부딪칠 돌 ])'),
('銅', 'copper'),
('東', 'East (one of the 4 directions)'),
('同', 'the same'),
('洞', 'a Dong, which is smaller than a Ku, which is smaller than a city'),
('場', 'grist'),
('場', 'a place, any place'),
('掄', 'lawn'),
('幕', 'curtain, screen, veil'),
('藐', 'booth, temporary shelter'),
('貘', 'tapir (a wild boar of  south America)'),
('脈', 'power or strength'),
('毛', 'a piece of hair, a toothbrush bristle'),
('妙', 'a mysterious power'),
('墓', 'a tomb'),
('犯', 'a transgression, a violation'),
('汴', '기뻐할 변 .  ㉠기뻐하다 ㉡좋아하다 ㉢기뻐하고 즐거워하는 모양'),
('辮', 'verbal defense.'),
('便', 'feces, stool'),
('浜', 'GI, grade of soldier'),
('本', 'this one, the one you are looking at'),
('剖', 'part, a section'),
('剖', 'bureau, department, ministry'),
('副', 'lucre, opulent, riches, wealth'),
('憤', 'anger'),
('非', 'not, negative (negates the following noun)'),
('箾', 'a capsule'),
('酸', 'an acid'),
('蔘', 'hemp, flax'),
('星', 'a stellar constellation'),
('稅', 'tax'),
('屬', 'a tribe,clan,relation'),
('屬', 'belong to, be affiliated with'),
('屬', 'a (biological) genus'),
('絉', 'skill, talent'),
('塍', '밭두둑 승'),
('室', 'a room'),
('壓', 'pressure'),
('液', 'juice, in  liquor'),
('額', 'the amount of'),
('年', 'a year'),
('鳶', 'a kite'),
('延', 'the total, a cable(''s) length'),
('靨', 'salt (table salt, ionic salt)'),
('欲', 'desire'),
('熨', 'cincture, enclosure (a ring fence)'),
('潤', 'burnish, gloss, sheen'),
('作', 'invenit, an opus'),
('橦', 'business'),
('橦', 'a counter for paper or other thin objects'),
('齎', 'stannous'),
('蔟', 'tribe'),
('蔟', 'a bunch of similar things, grouped together'),
('州', 'commonwealth, county, province'),
('週', 'a week, 7 days'),
('主', 'the main, the principle thing, the important thing'),
('輯', 'juice'),
('證', 'proof, evidence'),
('症', 'symptoms, signs of an illness'),
('津', 'resin, sap'),
('綴', 'binding, a file'),
('鰈', 'concubine, demimondaine'),
('廳', 'an administrative office'),
('醋', 'vinegar'),
('鏃', 'the end, the tip, the point'),
('珫', 'a gun'),
('螭', 'a korean measurement of distance, similar to feet'),
('他', 'others,other people'),
('縫', 'something bad, some trouble'),
('貪', 'greed'),
('糖', 'tongue'),
('糖', 'crack'),
('鍮', 'way, habit, style'),
('閉', 'to close, closing'),
('肺', 'lungs (animal anatomy, bellows (things like lungs)'),
('儤', 'cannonry, ordinance, package'),
('風', 'a stroke'),
('苾', 'fecit'),
('熇', 'nomy'),
('熇', 'crane'),
('函', 'a box for clothes or stuff'),
('合', 'conjunction, synthesis ; combined'),
('項', 'a mathematical term (e.g. a term in a series, etc.)'),
('詡', 'now'),
('烱', 'form, format, mold, size'),
('烱', 'punishment, a criminal sentence'),
('繯', 'ring'),
('垸', '환: 바르다, 칠하다'),
('換', 'a money exchange, changing currencies'),
('佸', 'a bow (for shooting arrows)'),
('罫', 'roost'),
('膾', 'sliced, raw fish (sushi)'),
('會', 'a meeting, an assembly'),
('匈', 'malignancy'),
('黖', 'a white color')
ON CONFLICT DO NOTHING;